"""initial_schema

Revision ID: 6819122e00b2
Revises: 
Create Date: 2026-02-18 18:56:08.961195+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6819122e00b2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('matviy_oq', 'yaltiroq_oq', 'qora_premium', 'gulli_3d', 'mramor_dizayn', 'led_podsvetka', 'yulduzli_osmon', 'ikki_darajali', 'ofis_minimal', 'oshxona', name='ceiling_category_groups'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('member_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('language_code', sa.String(length=8), server_default='uz', nullable=False),
    sa.Column('role', sa.Enum('client', 'installer', 'manager', 'admin', 'superadmin', name='user_role'), server_default='client', nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('media_file_id', sa.String(length=512), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('segment_filter', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'running', 'done', 'failed', name='broadcast_status'), server_default='draft', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broadcasts_scheduled', 'broadcasts', ['scheduled_at'], unique=False)
    op.create_index('ix_broadcasts_status', 'broadcasts', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('matviy_oq', 'yaltiroq_oq', 'qora_premium', 'gulli_3d', 'mramor_dizayn', 'led_podsvetka', 'yulduzli_osmon', 'ikki_darajali', 'ofis_minimal', 'oshxona', name='ceiling_category'), nullable=False),
    sa.Column('source_group_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('group', 'site', 'ads', 'deeplink', 'referral', name='lead_source'), server_default='group', nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('room_length', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('room_width', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('room_area', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('addons', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=64), nullable=True),
    sa.Column('utm_campaign', sa.String(length=64), nullable=True),
    sa.Column('assigned_manager_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('measurement', 'installation', name='appointment_type'), nullable=False),
    sa.Column('installer_id', sa.BigInteger(), nullable=True),
    sa.Column('brigade_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'done', 'cancelled', 'rescheduled', name='appointment_status'), server_default='scheduled', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['installer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_installer_date', 'appointments', ['installer_id', 'scheduled_at'], unique=False)
    op.create_index('ix_appointments_lead', 'appointments', ['lead_id'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'CONTACTED', 'MEASUREMENT', 'QUOTE', 'DEAL', 'INSTALLATION', 'COMPLETED', 'LOST', name='pipeline_stage'), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('matviy_oq', 'yaltiroq_oq', 'qora_premium', 'gulli_3d', 'mramor_dizayn', 'led_podsvetka', 'yulduzli_osmon', 'ikki_darajali', 'ofis_minimal', 'oshxona', name='ceiling_category_quotes'), nullable=False),
    sa.Column('base_price_per_sqm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('district_modifier', sa.Numeric(precision=4, scale=2), server_default='1.00', nullable=False),
    sa.Column('addons_detail', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='UZS', nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quotes_lead', 'quotes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_lead', table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('pipeline_stages')
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_lead', table_name='appointments')
    op.drop_index('ix_appointments_installer_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('leads')
    op.drop_index('ix_broadcasts_status', table_name='broadcasts')
    op.drop_index('ix_broadcasts_scheduled', table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
